# Mosquitto: broker MQTT del servidor central.
persistence true
persistence_location /mosquitto/data/
log_dest stdout

# Listener MQTT nativo (dispositivos ESP32)
listener 1883
protocol mqtt
allow_anonymous true

# Listener MQTT over WebSocket (dashboard)
listener 9001
protocol websockets
allow_anonymous true
